[package]
name = "s3-compat-spec"
version = "0.1.0"
edition = "2024"

[dependencies]
crc-fast = "1.9.0"
aws-config = "1.8.15"
aws-credential-types = "1"
aws-sdk-s3 = "1.128.0"
base64 = "0.22"
bytes = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "1.1.2"
s3-mock-server = { git = "https://github.com/awslabs/aws-s3-transfer-manager-rs", branch = "s3-tm-vnext" }
similar = "2"
regex = "1"
tempfile = "3"
aws-smithy-types = "1"
tracing = "0.1"

[dev-dependencies]
tempfile = "3.27.0"
