[package]
name = "s3-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Native Rust implementation of the aws s3 CLI subcommand"
publish = false

[profile.release]
# opt-level = "z"     # Optimize for size (use "s" for a slight speed/size balance)
lto = true          # Enable Link Time Optimization (can be "thin" or "fat")
codegen-units = 1   # Maximize optimization opportunities across the whole crate

[[bin]]
name = "aws"
path = "src/main.rs"

[lib]
name = "s3_cli"
path = "src/lib.rs"

[dependencies]
aws-config = { version = "1", default-features = false, features = ["rt-tokio", "default-https-client", "sso", "credentials-process"] }
aws-sdk-s3 = { version = "1" }
aws-smithy-types = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
thiserror = "2"
jiff = "0.2"
libc = "0.2"
tracing = "0.1"
aws-smithy-http-client = { version = "1.1.12", features = ["rustls-aws-lc"] }
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
aws-smithy-runtime-api = { version = "1.12.0", features = ["client"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2.0"
aws-runtime = "1.7.3"
aws-types = "1.3.15"
mime_guess2 = "2.3"

[dependencies.aws-sdk-s3-transfer-manager]
path = "/Users/todaaron/sandbox/rs/aws-s3-transfer-manager-rs/aws-sdk-s3-transfer-manager"

[dev-dependencies]
aws-smithy-mocks = "0.2"
aws-credential-types = { version = "1", features = ["test-util"] }
aws-smithy-async = "1"
vt100 = "0.16"
tempfile = "3.27.0"

[dev-dependencies.aws-sdk-s3]
version = "1"
features = ["test-util"]
